### ISSUE TITLE
Can't call method purge on unblessed reference at dmarcts-report-parser.pl

### ISSUE THREAD

**Issue by DanielV88** [techsneeze/dmarcts-report-parser#22] opened 2017-03-30 08:17 UTC
Hi,

I have a problem running the script after a few months of using this.
The system is giving the following error with debugging:

[root@dmarc dmarcts-report-parser]# ./dmarcts-report-parser.pl -d
There are 207 messages in the Inbox folder.
--------------------------------
The Current Message UID is: 169
--------------------------------
Subject: MimeType: multipart/report
/tmp/msg-2609-1.txt
/tmp/msg-2609-2.msg
Use of uninitialized value in print at ./dmarcts-report-parser.pl line 463.

Can't call method "purge" on unblessed reference at ./dmarcts-report-parser.pl line 466.

**Comment by techsneeze** [comment] 2017-04-29 06:33
Every time I've seen this, it was due to a non-DMARC message being in that mailbox.  It might be some other spam, NDR, etc that got delivered to that mailbox?

**Comment by jobisoft** [comment] 2017-05-30 19:53
I also have that error, and techsneeze is right, it is caused by an email which is not a report. However such an email should not kill the script. The crash is causes by this line:

https://github.com/techsneeze/dmarcts-report-parser/blob/master/dmarcts-report-parser.pl#L470

which is already in the final "else" part for "this is not a report". Why do we purge the element "$ent->parts($i)->{ME_Bodyhandle}" if we know that this is not a valid report and thus have no guarantee, that this element is there in the first place? In my "bad" email, this element is indeed undef.

A fix which worked for me is to replace line 470 by:

if($ent->parts($i)->{ME_Bodyhandle}) {$ent->parts($i)->{ME_Bodyhandle}->purge;}

But why do we purge there at all? In line 516 we purge the entire $ent. My perl knowledge is to limited, to answer that question. 

I can create a pull request for my simple fix, if you want.

**Comment by jobisoft** [comment] 2017-05-31 07:01
I just created the pull request.

**Comment by techsneeze** [comment] 2017-06-01 05:45
Thanks for identifying the problem and submitting the pull request!  The request has been merged now.

**Comment by lwt-pressy** [comment] 2017-07-25 18:01
@techsneeze / @jobisoft  can this issue be closed?

**Closed as completed** 2017-07-25 19:09 UTC
