### ISSUE TITLE
Error while connecting to database [mariadb 10.1]

### ISSUE THREAD

**Issue by EnochTheWise** [techsneeze/dmarcts-report-parser#29] opened 2017-06-27 05:25 UTC
Hi, i'm decided to try your utility.
Configured:
egrep "dbname|dbhost" dmarcts-report-parser.conf 
$dbname = 'dmarcreports';
$dbhost = 'localhost:3306'; # Set the hostname if we can't connect to the local socket.
The values of variables $dbuser and  $dbpass are actual.

But I get an error:
./dmarcts-report-parser.pl  -i
Use of uninitialized value $dbname in concatenation (.) or string at ./dmarcts-report-parser.pl line 193.
Use of uninitialized value $dbhost in concatenation (.) or string at ./dmarcts-report-parser.pl line 193.
DBI connect('database=;host=','',...) failed: Access denied for user 'john'@'localhost' (using password: NO) at ./dmarcts-report-parser.pl line 193.
Cannot connect to database

what's wrong? 8)

**Comment by wioxjk** [comment] 2017-07-24 07:45
` Access denied for user 'john'@'localhost' (using password: NO) at ./dmarcts-report-parser.pl line 193.`

Please set your password

**Comment by EnochTheWise** [comment] 2017-07-24 10:07
> Please set your password

As I wrote above:
"The values of variables $dbuser and $dbpass are actual."
e.g.:
$dbname = 'dmarcreports';
$dbuser = 'john';
$dbpass = '121212121';
$dbhost = 'localhost';

DB started at localhost:
$ netstat -ant | grep 3306
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN

**Comment by wioxjk** [comment] 2017-07-24 12:03
Oh, sorry about that!

Are you able to connect to the database?
mysql -ujohn -p121212121

**Comment by EnochTheWise** [comment] 2017-07-24 12:45
> Are you able to connect to the database?
> mysql -ujohn -p121212121

Yes

PS MB problem is here:
>>Use of uninitialized value $dbhost in concatenation (.) or string at ./dmarcts-report-parser.pl line 193.
>>DBI connect('database=;host=','',...)

Variables is not set^^^^^^^^^^

**Comment by wioxjk** [comment] 2017-07-24 13:38
Yeah I got the same problem, I am using MariaDB too.
Do you know if it works with mySQL?

**Comment by wioxjk** [comment] 2017-07-24 13:38
@techsneeze

**Comment by techsneeze** [comment] 2017-07-24 16:47
This definitely works with mySQL, and has been used against a variety of versions.

I know there was a previous person who had submitted some changes, as mariaDB was being more strict on some of the input.  Those changes were submitted and fixed his problem.  

This looks like a fairly basic level of problem though, as you aren't even able to connect to the DB.  Is it perhaps trying to connect on the IPv6 address, and you don't have DB permissions set on the IPv6 port?  It is a longshot... but you could try changing dbhost to 127.0.0.1

**Comment by lwt-pressy** [comment] 2017-07-24 17:42
As for mariadb, i use it (debian V9) and have no problems. So it is no general mariadb problem.

**Comment by lwt-pressy** [comment] 2017-07-24 18:30
@wioxjk - i can reproduce your error. I never get it because i call by path. If called directly in the directory it won't run somehow anymore (sorry, I'm no perl expert).

Could you try to change line 129 from:
    do $conf_file;
to:
   do "./$conf_file";

here this change works.

**Comment by lwt-pressy** [comment] 2017-07-24 18:39
the explanation is on [perldoc - do](https://perldoc.perl.org/functions/do.html)

Using do with a relative path (except for ./ and ../), like

        do 'foo/stat.pl';

will search the @INC directories, and update %INC if the file is found. See @INC in perlvar and %INC in perlvar for these variables. **In particular, note that whilst historically @INC contained '.' (the current directory) making these two cases equivalent, that is no longer necessarily the case, as '.' is not included in @INC by default in perl versions 5.26.0 onwards.** Instead, perl will now warn:

**Comment by techsneeze** [comment] 2017-07-24 23:46
The pull request has been merged, as requested.  Does this resolve the issue?

**Comment by EnochTheWise** [comment] 2017-07-25 03:14
> Does this resolve the issue?

yes, but there was another error:
`DBD::mysql::db do failed: Specified key was too long; max key length is 767 bytes at ./dmarcts-report-parser.pl line 816.
Use of uninitialized value in concatenation (.) or string at ./dmarcts-report-parser.pl line 233.`

Full output: https://pastebin.com/2hLCL3eR

**Comment by wioxjk** [comment] 2017-07-25 11:16
@lwt-pressy 
I did try that and I it worked, got the same issue as @EnochTheWise 

I decided to move down to mysql instead

**Comment by lwt-pressy** [comment] 2017-07-25 17:32
@EnochTheWise could please put the new error in a new issue.

**Closed as completed** 2017-07-26 05:07 UTC
