### ISSUE TITLE
Use of uninitialized value $dbname in concatenation (.) or string at

### ISSUE THREAD

**Issue by wioxjk** [techsneeze/dmarcts-report-parser#30] opened 2017-07-24 13:38 UTC
Hi,
I got the following when I am trying to run the script. The config file is populated with correct information

```
root@dmarc-parser:~/dmarcts-report-parser# ./dmarcts-report-parser.pl -i 
Use of uninitialized value $dbname in concatenation (.) or string at ./dmarcts-report-parser.pl line 193.
Use of uninitialized value $dbhost in concatenation (.) or string at ./dmarcts-report-parser.pl line 193.
DBD::mysql::db selectall_arrayref failed: No database selected at ./dmarcts-report-parser.pl line 778.
Can't use an undefined value as an ARRAY reference at ./dmarcts-report-parser.pl line 778.
```

**Comment by lwt-pressy** [comment] 2017-07-24 18:46
@techsneeze should be duplicate of #29

**Closed as completed** 2017-07-24 23:40 UTC
